apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
      - name: data-processor
        image: <image-location/data-processor:tag>
        ports:
        - containerPort: 8080
